import argon2 from 'argon2';
import crypto from 'node:crypto';
import cookieParser from 'cookie-parser';
import cors from 'cors';
import express from 'express';
import helmet from 'helmet';
import rateLimit from 'express-rate-limit';
import { z } from 'zod';
import { createSession, deleteSession, getSession } from './auth/sessions.js';
import { scoreRequestSchema, toDatabaseScore } from './scoring.js';

const registerTeam = z.object({ teamName: z.string().trim().min(1).max(160), leaderName: z.string().trim().min(1).max(160), leaderEmail: z.string().trim().email(), college: z.string().trim().max(160).optional().or(z.literal('')), loginName: z.string().trim().min(3).max(80).regex(/^[a-zA-Z0-9-]+$/), password: z.string().min(8).max(256) }).strict();
const participantLogin = z.object({ identifier: z.string().trim().min(1).max(80), password: z.string().min(1).max(256) }).strict();
const problemStatement = z.object({ title: z.string().trim().min(1).max(200), description: z.string().trim().min(1).max(10000), isActive: z.boolean().optional() }).strict();
const submission = z.object({ problemStatementId: z.string().uuid(), projectTitle: z.string().trim().min(1).max(200), description: z.string().trim().min(1).max(10000), techStack: z.string().trim().max(1000).optional().or(z.literal('')), repositoryUrl: z.string().url().max(2048).optional().or(z.literal('')), deployedUrl: z.string().url().max(2048).optional().or(z.literal('')), status: z.enum(['draft', 'submitted', 'final']).optional() }).strict();
const announcement = z.object({ title: z.string().trim().min(1).max(200), content: z.string().trim().min(1).max(10000), priority: z.enum(['normal', 'important', 'urgent']).optional() }).strict();
const norm = (value) => value.trim().toLowerCase();
const errors = { 400: ['BAD_REQUEST', 'Request could not be processed'], 401: ['UNAUTHORIZED', 'Invalid login credentials'], 403: ['FORBIDDEN', 'Request is not allowed'], 404: ['NOT_FOUND', 'Not found'], 409: ['CONFLICT', 'Team name or login name already exists'], 429: ['RATE_LIMITED', 'Too many requests'], 503: ['SERVICE_UNAVAILABLE', 'Service temporarily unavailable'] };
function fail(status) { const [code, message] = errors[status] || ['INTERNAL_ERROR', 'Internal server error']; return { error: { code, message } }; }
function errorStatus(error) { if (error?.name === 'ZodError' || error?.type === 'entity.parse.failed') return 400; if (error?.code === '23505') return 409; return Number.isInteger(error?.statusCode) ? error.statusCode : 500; }
function requirePool(pool) { if (!pool || typeof pool.query !== 'function' || typeof pool.connect !== 'function') { const error = new Error('Database unavailable'); error.statusCode = 503; throw error; } }
function cookieOptions(config) { return { httpOnly: true, secure: config.nodeEnv === 'production', sameSite: config.nodeEnv === 'production' ? 'none' : 'lax', path: '/', maxAge: config.sessionTtlHours * 3600000 }; }
function userDto(user) { return { id: user.id, email: user.email, name: user.name || user.display_name, role: user.role, ...(user.teamId || user.team_id ? { teamId: user.teamId || user.team_id } : {}) }; }
async function serviceUser(pool, { email, name, role, password }) {
  const passwordHash = await argon2.hash(password, { type: argon2.argon2id });
  return (await pool.query(`INSERT INTO users (email, display_name, role, password_hash) VALUES ($1,$2,$3,$4) ON CONFLICT (email) DO UPDATE SET display_name=EXCLUDED.display_name, role=EXCLUDED.role, password_hash=EXCLUDED.password_hash, enabled=TRUE, updated_at=NOW() RETURNING id,email,display_name,role,team_id`, [norm(email), name, role, passwordHash])).rows[0];
}
function mapTeam(row) { return { id: row.id, team_name: row.team_name, leader_name: row.leader_name, leader_email: row.leader_email, college: row.college, created_at: row.created_at, updated_at: row.updated_at, project_title: row.project_title, project_description: row.project_description, tech_stack: row.tech_stack, github_link: row.github_link, demo_link: row.demo_link, submission_status: row.submission_status || 'not_submitted', team_members: row.team_members || [], scores: row.scores || [] }; }

export function createApp({ pool, config, logger = console } = {}) {
  if (!config) throw new Error('Server configuration is required');
  const app = express(); app.disable('x-powered-by'); if (config.nodeEnv === 'production') app.set('trust proxy', 1);
  app.use(helmet()); app.use(cors({ origin: (origin, callback) => { if (!origin || origin === config.frontendOrigin) return callback(null, true); const error = new Error('Origin denied'); error.statusCode = 403; return callback(error); }, credentials: true })); app.use(express.json({ limit: '100kb' })); app.use(cookieParser()); app.use(rateLimit({ windowMs: 900000, limit: 100, standardHeaders: 'draft-7', legacyHeaders: false }));
  async function auth(req, res, next) { try { requirePool(pool); const session = await getSession(pool, req.cookies?.[config.sessionCookieName]); if (!session) return res.status(401).json(fail(401)); req.session = session; next(); } catch (error) { next(error); } }
  const role = (...roles) => [auth, (req, res, next) => roles.includes(req.session.role) ? next() : res.status(403).json(fail(403))];
  async function establish(res, user) { const token = await createSession(pool, user, config.sessionTtlHours); res.cookie(config.sessionCookieName, token, cookieOptions(config)); res.json({ user: userDto(user) }); }

  app.get('/api/health', (_req, res) => res.json({ status: 'ok' }));
  app.post('/api/auth/organizer/login', async (req, res, next) => { try { if (norm(String(req.body?.email || '')) !== norm(config.organizerEmail) || req.body?.password !== config.organizerPassword) return res.status(401).json(fail(401)); requirePool(pool); const user = await serviceUser(pool, { email: config.organizerEmail, name: 'Organizer', role: 'organizer', password: config.organizerPassword }); await establish(res, user); } catch (error) { next(error); } });
  const generateJudgePassword = async (_req, res, next) => { try { requirePool(pool); const password = crypto.randomBytes(12).toString('hex').toUpperCase(); const passwordHash = await argon2.hash(password, { type: argon2.argon2id }); await pool.query('INSERT INTO judge_credentials (judge_id,password_hash) VALUES ($1,$2) ON CONFLICT (judge_id) DO UPDATE SET password_hash=EXCLUDED.password_hash,created_at=NOW()', [config.judgeId, passwordHash]); res.json({ judgeId: config.judgeId, password }); } catch (error) { next(error); } };
  app.post('/api/auth/judge/generate-password', ...role('organizer'), generateJudgePassword);
  app.post('/api/auth/judge/password', ...role('organizer'), generateJudgePassword);
  app.post('/api/auth/judge/login', async (req, res, next) => { let client; try { if (req.body?.judgeId !== config.judgeId) return res.status(401).json(fail(401)); requirePool(pool); client = await pool.connect(); await client.query('BEGIN'); const credential = (await client.query('SELECT password_hash FROM judge_credentials WHERE judge_id=$1 FOR UPDATE', [config.judgeId])).rows[0]; if (!credential || !(await argon2.verify(credential.password_hash, String(req.body?.password || '')))) { await client.query('ROLLBACK'); return res.status(401).json(fail(401)); } await client.query('DELETE FROM judge_credentials WHERE judge_id=$1', [config.judgeId]); await client.query('COMMIT'); const user = await serviceUser(pool, { email: `${config.judgeId.toLowerCase()}@bitandbuild.com`, name: config.judgeId, role: 'judge', password: crypto.randomBytes(32).toString('hex') }); await establish(res, user); } catch (error) { if (client) await client.query('ROLLBACK').catch(() => {}); next(error); } finally { client?.release(); } });
  app.post('/api/auth/participant/login', async (req, res, next) => { try { const input = participantLogin.parse(req.body); requirePool(pool); const result = await pool.query(`SELECT c.team_id,c.password_hash,u.id,u.email,u.display_name,u.enabled FROM team_credentials c JOIN users u ON u.team_id=c.team_id AND u.role='participant' WHERE c.login_name=$1`, [norm(input.identifier)]); const record = result.rows[0]; if (!record || !record.enabled || !(await argon2.verify(record.password_hash, input.password))) return res.status(401).json(fail(401)); await establish(res, { id: record.id, email: record.email, name: record.display_name, role: 'participant', teamId: record.team_id }); } catch (error) { next(error); } });
  app.get('/api/auth/me', auth, (req, res) => res.json({ user: userDto(req.session) }));
  app.post('/api/auth/logout', auth, async (req, res, next) => { try { await deleteSession(pool, req.cookies?.[config.sessionCookieName]); const { maxAge, ...options } = cookieOptions(config); res.clearCookie(config.sessionCookieName, options); res.json({ success: true }); } catch (error) { next(error); } });

  app.post('/api/teams', ...role('organizer'), async (req, res, next) => { let client; try { const input = registerTeam.parse(req.body); requirePool(pool); client = await pool.connect(); await client.query('BEGIN'); const passwordHash = await argon2.hash(input.password, { type: argon2.argon2id }); const team = (await client.query('INSERT INTO teams (team_name,leader_name,leader_email,college) VALUES ($1,$2,$3,$4) RETURNING *', [input.teamName, input.leaderName, norm(input.leaderEmail), input.college || null])).rows[0]; await client.query("INSERT INTO team_members (team_id,name,email,role) VALUES ($1,$2,$3,'Leader')", [team.id, input.leaderName, norm(input.leaderEmail)]); await client.query("INSERT INTO users (email,display_name,role,password_hash,team_id) VALUES ($1,$2,'participant',$3,$4)", [norm(input.leaderEmail), input.leaderName, passwordHash, team.id]); const loginName = norm(input.loginName); await client.query('INSERT INTO team_credentials (team_id,login_name,password_hash) VALUES ($1,$2,$3)', [team.id, loginName, passwordHash]); await client.query('COMMIT'); res.status(201).json({ team: { id: team.id, teamName: team.team_name, leaderName: team.leader_name, leaderEmail: team.leader_email, college: team.college }, credentials: { loginName } }); } catch (error) { if (client) await client.query('ROLLBACK'); next(error); } finally { client?.release(); } });
  const teamSelectBase = `SELECT t.*,s.title project_title,s.description project_description,s.tech_stack,s.github_url github_link,s.demo_url demo_link,COALESCE(s.status,'not_submitted') submission_status,COALESCE((SELECT json_agg(json_build_object('id',m.id,'member_name',m.name,'member_email',m.email,'member_role',m.role)) FROM team_members m WHERE m.team_id=t.id),'[]'::json) team_members`;
  const teamSelect = `${teamSelectBase},COALESCE((SELECT json_agg(sc ORDER BY sc.created_at DESC) FROM scores sc WHERE sc.team_id=t.id),'[]'::json) scores FROM teams t LEFT JOIN submissions s ON s.team_id=t.id`;
  const participantTeamSelect = `${teamSelectBase},'[]'::json AS scores FROM teams t LEFT JOIN submissions s ON s.team_id=t.id`;
  app.get('/api/teams', ...role('organizer'), async (_req, res, next) => { try { const result = await pool.query(`${teamSelect} ORDER BY t.created_at DESC`); res.json({ teams: result.rows.map(mapTeam) }); } catch (error) { next(error); } });
  app.get('/api/teams/me', ...role('participant'), async (req, res, next) => { try { const result = await pool.query(`${participantTeamSelect} WHERE t.id=$1`, [req.session.teamId]); if (!result.rows[0]) return res.status(404).json(fail(404)); res.json({ team: mapTeam(result.rows[0]) }); } catch (error) { next(error); } });
  app.get('/api/problem-statements', auth, async (req, res, next) => { try { const result = await pool.query(`SELECT id,title,description,is_active,created_at,updated_at FROM problem_statements ${req.session.role === 'organizer' ? '' : 'WHERE is_active=TRUE'} ORDER BY created_at DESC`); res.json({ problemStatements: result.rows }); } catch (error) { next(error); } });
  app.post('/api/problem-statements', ...role('organizer'), async (req, res, next) => { try { const input = problemStatement.parse(req.body); const result = await pool.query('INSERT INTO problem_statements (title,description,is_active) VALUES ($1,$2,$3) RETURNING *', [input.title, input.description, input.isActive ?? true]); res.status(201).json({ problemStatement: result.rows[0] }); } catch (error) { next(error); } });
  app.put('/api/problem-statements/:id', ...role('organizer'), async (req, res, next) => { try { const input = problemStatement.parse(req.body); const result = await pool.query('UPDATE problem_statements SET title=$1,description=$2,is_active=$3,updated_at=NOW() WHERE id=$4 RETURNING *', [input.title, input.description, input.isActive ?? true, req.params.id]); if (!result.rows[0]) return res.status(404).json(fail(404)); res.json({ problemStatement: result.rows[0] }); } catch (error) { next(error); } });
  app.delete('/api/problem-statements/:id', ...role('organizer'), async (req, res, next) => { try { const result = await pool.query('DELETE FROM problem_statements WHERE id=$1 RETURNING id', [req.params.id]); if (!result.rows[0]) return res.status(404).json(fail(404)); res.status(204).end(); } catch (error) { next(error); } });
  const submissionSelect = `SELECT s.id,s.team_id,s.problem_statement_id,s.title,s.description,s.tech_stack,s.github_url AS repository_url,s.demo_url AS deployed_url,s.status,s.submitted_at,s.created_at,s.updated_at,t.team_name,t.leader_name,p.title AS problem_statement_title FROM submissions s JOIN teams t ON t.id=s.team_id LEFT JOIN problem_statements p ON p.id=s.problem_statement_id`;
  app.post('/api/submissions', ...role('participant'), async (req, res, next) => { try { const input = submission.parse(req.body); const result = await pool.query(`INSERT INTO submissions (team_id,problem_statement_id,title,description,tech_stack,github_url,demo_url,status,submitted_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,CASE WHEN $8='submitted' THEN NOW() ELSE NULL END) ON CONFLICT (team_id) DO UPDATE SET problem_statement_id=EXCLUDED.problem_statement_id,title=EXCLUDED.title,description=EXCLUDED.description,tech_stack=EXCLUDED.tech_stack,github_url=EXCLUDED.github_url,demo_url=EXCLUDED.demo_url,status=EXCLUDED.status,submitted_at=CASE WHEN EXCLUDED.status='submitted' THEN NOW() ELSE submissions.submitted_at END,updated_at=NOW() WHERE submissions.status <> 'final' RETURNING *`, [req.session.teamId,input.problemStatementId,input.projectTitle,input.description,input.techStack || null,input.repositoryUrl || null,input.deployedUrl || null,input.status || 'submitted']); if (!result.rows[0]) return res.status(403).json(fail(403)); res.status(201).json({ submission: result.rows[0] }); } catch (error) { next(error); } });
  app.get('/api/submissions/me', ...role('participant'), async (req, res, next) => { try { const result = await pool.query(`${submissionSelect} WHERE s.team_id=$1`, [req.session.teamId]); res.json({ submissions: result.rows }); } catch (error) { next(error); } });
  app.put('/api/submissions/:id', auth, async (req, res, next) => { try { const input = submission.parse(req.body); const isParticipant = req.session.role === 'participant'; if (!isParticipant && req.session.role !== 'organizer') return res.status(403).json(fail(403)); const values = [input.problemStatementId,input.projectTitle,input.description,input.techStack || null,input.repositoryUrl || null,input.deployedUrl || null,input.status || 'submitted',req.params.id]; const ownership = isParticipant ? ' AND team_id=$9 AND status <> \'final\'' : ''; if (isParticipant) values.push(req.session.teamId); const result = await pool.query(`UPDATE submissions SET problem_statement_id=$1,title=$2,description=$3,tech_stack=$4,github_url=$5,demo_url=$6,status=$7,submitted_at=CASE WHEN $7='submitted' THEN NOW() ELSE submitted_at END,updated_at=NOW() WHERE id=$8${ownership} RETURNING *`, values); if (!result.rows[0]) return res.status(404).json(fail(404)); res.json({ submission: result.rows[0] }); } catch (error) { next(error); } });
  app.get('/api/admin/submissions', ...role('organizer'), async (_req, res, next) => { try { const result = await pool.query(`${submissionSelect} ORDER BY s.updated_at DESC`); res.json({ submissions: result.rows }); } catch (error) { next(error); } });
  app.get('/api/judge/submissions', ...role('judge'), async (req, res, next) => { try { const result = await pool.query(`SELECT s.id,s.team_id,s.problem_statement_id,s.title,s.description,s.tech_stack,s.github_url AS repository_url,s.demo_url AS deployed_url,s.status,s.submitted_at,s.created_at,s.updated_at,t.team_name,t.leader_name,p.title AS problem_statement_title,sc.id AS score_id,sc.completeness,sc.technical_execution,sc.innovation_creativity,sc.applicability_scalability,sc.ui_ux,sc.bonus_features,sc.presentation,sc.work_distribution,sc.weighted_scores,sc.final_score,sc.comments FROM submissions s JOIN teams t ON t.id=s.team_id LEFT JOIN problem_statements p ON p.id=s.problem_statement_id LEFT JOIN scores sc ON sc.team_id=s.team_id AND sc.judge_id=$1 WHERE s.status IN ('submitted','under_review','final') ORDER BY s.submitted_at DESC`, [req.session.id]); res.json({ submissions: result.rows }); } catch (error) { next(error); } });
  app.post('/api/scores', ...role('judge'), async (req, res, next) => { try { const payload = scoreRequestSchema.parse(req.body); const submissionRecord = (await pool.query("SELECT id FROM submissions WHERE team_id=$1 AND status IN ('submitted','under_review','final')", [payload.team_id])).rows[0]; if (!submissionRecord) return res.status(404).json(fail(404)); const score = toDatabaseScore(payload); const values = [score.teamId,submissionRecord.id,req.session.id,req.session.email,score.innovationCreativity,score.technicalExecution,score.uiUx,score.presentation,score.completeness,score.technicalExecution,score.innovationCreativity,score.applicabilityScalability,score.uiUx,score.bonusFeatures,score.workDistribution,score.weightedScores,score.finalScore,score.comments]; const result = await pool.query(`INSERT INTO scores (team_id,submission_id,judge_id,judge_email,innovation,technical,design,presentation,completeness,technical_execution,innovation_creativity,applicability_scalability,ui_ux,bonus_features,work_distribution,weighted_scores,final_score,comments) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18) ON CONFLICT (team_id,judge_email) DO UPDATE SET submission_id=EXCLUDED.submission_id,judge_id=EXCLUDED.judge_id,innovation=EXCLUDED.innovation,technical=EXCLUDED.technical,design=EXCLUDED.design,presentation=EXCLUDED.presentation,completeness=EXCLUDED.completeness,technical_execution=EXCLUDED.technical_execution,innovation_creativity=EXCLUDED.innovation_creativity,applicability_scalability=EXCLUDED.applicability_scalability,ui_ux=EXCLUDED.ui_ux,bonus_features=EXCLUDED.bonus_features,work_distribution=EXCLUDED.work_distribution,weighted_scores=EXCLUDED.weighted_scores,final_score=EXCLUDED.final_score,comments=EXCLUDED.comments,updated_at=NOW() RETURNING *`, values); res.json({ score: result.rows[0] }); } catch (error) { next(error); } });
  app.get('/api/admin/scores', ...role('organizer'), async (_req, res, next) => { try { const result = await pool.query(`SELECT sc.*,t.team_name,s.title AS submission_title FROM scores sc JOIN teams t ON t.id=sc.team_id LEFT JOIN submissions s ON s.id=sc.submission_id ORDER BY sc.updated_at DESC`); res.json({ scores: result.rows }); } catch (error) { next(error); } });
  app.get('/api/announcements', auth, async (_req, res, next) => { try { const result = await pool.query('SELECT id,title,content,priority,is_active,created_at,updated_at FROM announcements WHERE is_active=TRUE ORDER BY created_at DESC'); res.json({ announcements: result.rows }); } catch (error) { next(error); } });
  app.post('/api/announcements', ...role('organizer'), async (req, res, next) => { try { const input = announcement.parse(req.body); const result = await pool.query('INSERT INTO announcements (title,content,priority) VALUES ($1,$2,$3) RETURNING *', [input.title, input.content, input.priority || 'normal']); res.status(201).json({ announcement: result.rows[0] }); } catch (error) { next(error); } });
  app.delete('/api/announcements/:id', ...role('organizer'), async (req, res, next) => { try { const result = await pool.query('DELETE FROM announcements WHERE id=$1 RETURNING id', [req.params.id]); if (!result.rows[0]) return res.status(404).json(fail(404)); res.status(204).end(); } catch (error) { next(error); } });
  app.use((_req, res) => res.status(404).json(fail(404))); app.use((error, req, res, _next) => { if (res.headersSent) return; const status = errorStatus(error); logger.error?.({ event: 'http_error', status, method: req.method, path: req.path, errorType: error?.name || 'Error' }); res.status(status).json(fail(status)); }); return app;
}
